#!/usr/bin/env Rscript

# Enrich the exact ranked BRCA gene hand-off generated by selection.py.
# No static gene list and no alternative enrichment method are used here.

usage <- function() {
  paste(
    "Usage: Rscript enrichr_brca.R --genes SELECTED_GENES.csv",
    "--output-dir NEW_DIRECTORY [--config enrichr_config.json]",
    sep = " "
  )
}

parse_arguments <- function(arguments, default_config) {
  parsed <- list(genes = NULL, output_dir = NULL, config = default_config)
  index <- 1L
  while (index <= length(arguments)) {
    option <- arguments[[index]]
    if (option %in% c("--help", "-h")) {
      cat(usage(), "\n")
      quit(status = 0)
    }
    if (!(option %in% c("--genes", "--output-dir", "--config"))) {
      stop("Unknown argument: ", option, "\n", usage(), call. = FALSE)
    }
    if (index == length(arguments)) {
      stop("Missing value for ", option, call. = FALSE)
    }
    field <- sub("^--", "", option)
    field <- gsub("-", "_", field, fixed = TRUE)
    parsed[[field]] <- arguments[[index + 1L]]
    index <- index + 2L
  }
  if (is.null(parsed$genes) || is.null(parsed$output_dir)) {
    stop("--genes and --output-dir are required.\n", usage(), call. = FALSE)
  }
  parsed
}

abort_missing_packages <- function(packages) {
  missing <- packages[!vapply(packages, requireNamespace, logical(1), quietly = TRUE)]
  if (length(missing) > 0L) {
    stop(
      "Missing R package(s): ", paste(missing, collapse = ", "),
      ". Install exactly the packages documented in analysis/brca/r/README.md.",
      call. = FALSE
    )
  }
}

normalise_enrichr_table <- function(table, library_name) {
  table <- as.data.frame(table, stringsAsFactors = FALSE, check.names = FALSE)
  if (ncol(table) == 0L) return(data.frame(Gene_set = character()))
  rename <- c(
    "P.value" = "P-value",
    "Adjusted.P.value" = "Adjusted P-value",
    "Old.P.value" = "Old P-value",
    "Old.Adjusted.P.value" = "Old Adjusted P-value",
    "Odds.Ratio" = "Odds Ratio",
    "Combined.Score" = "Combined Score"
  )
  for (old in names(rename)) {
    if (old %in% names(table) && !(rename[[old]] %in% names(table))) {
      names(table)[names(table) == old] <- rename[[old]]
    }
  }
  table$Gene_set <- library_name
  table
}

bind_tables <- function(tables) {
  tables <- Filter(function(value) ncol(value) > 0L, tables)
  if (length(tables) == 0L) {
    return(data.frame())
  }
  all_columns <- unique(unlist(lapply(tables, names), use.names = FALSE))
  aligned <- lapply(tables, function(table) {
    missing <- setdiff(all_columns, names(table))
    for (column in missing) table[[column]] <- NA
    table[all_columns]
  })
  do.call(rbind, aligned)
}

filter_terms <- function(table, threshold, top_n) {
  required <- c("Term", "Adjusted P-value")
  if (!all(required %in% names(table))) {
    warning("Enrichr result does not contain required columns: ", paste(required, collapse = ", "))
    return(data.frame())
  }
  adjusted <- suppressWarnings(as.numeric(table[["Adjusted P-value"]]))
  keep <- !is.na(adjusted) & adjusted < threshold
  result <- table[keep, , drop = FALSE]
  result[["Adjusted P-value"]] <- adjusted[keep]
  result <- result[order(result[["Adjusted P-value"]]), , drop = FALSE]
  result <- head(result, top_n)
  if (nrow(result) == 0L) return(result)

  result$Display_term <- gsub("\\s*\\(GO:[0-9]+\\)\\s*$", "", as.character(result$Term))
  result$minus_log10_padj <- -log10(pmax(result[["Adjusted P-value"]], .Machine$double.xmin))
  if ("Overlap" %in% names(result)) {
    pieces <- strsplit(as.character(result$Overlap), "/", fixed = TRUE)
    result$Count <- suppressWarnings(as.numeric(vapply(pieces, `[`, "", 1L)))
    result$Term_size <- suppressWarnings(as.numeric(vapply(pieces, `[`, "", 2L)))
    result$Overlap_ratio <- result$Count / result$Term_size
  }
  result
}

save_bar_plot <- function(table, title, threshold, output_file) {
  if (nrow(table) == 0L) return(invisible(FALSE))
  plot_data <- table[order(table$minus_log10_padj), , drop = FALSE]
  chart <- ggplot2::ggplot(
    plot_data,
    ggplot2::aes(x = reorder(Display_term, minus_log10_padj), y = minus_log10_padj)
  ) +
    ggplot2::geom_col(fill = "steelblue", colour = "black", linewidth = 0.25) +
    ggplot2::coord_flip() +
    ggplot2::geom_hline(
      yintercept = -log10(threshold), linetype = "dashed", colour = "red"
    ) +
    ggplot2::labs(
      title = paste(title, "Enrichment in TCGA-BRCA"),
      x = NULL,
      y = "-log10(adjusted P-value)"
    ) +
    ggplot2::theme_minimal(base_size = 12)
  ggplot2::ggsave(output_file, chart, width = 10, height = max(6, 0.55 * nrow(plot_data) + 2), dpi = 300)
  invisible(TRUE)
}

save_dot_plot <- function(table, title, output_file) {
  required <- c("Overlap_ratio", "Count", "minus_log10_padj", "Display_term")
  if (nrow(table) == 0L || !all(required %in% names(table))) return(invisible(FALSE))
  plot_data <- table[stats::complete.cases(table[required]), , drop = FALSE]
  if (nrow(plot_data) == 0L) return(invisible(FALSE))
  chart <- ggplot2::ggplot(
    plot_data,
    ggplot2::aes(
      x = Overlap_ratio,
      y = reorder(Display_term, Overlap_ratio),
      size = Count,
      colour = minus_log10_padj
    )
  ) +
    ggplot2::geom_point() +
    ggplot2::scale_colour_gradient(low = "mistyrose", high = "firebrick") +
    ggplot2::labs(
      title = paste(title, "Enrichment in TCGA-BRCA"),
      x = "Overlap ratio (submitted genes / term size)",
      y = NULL,
      colour = "-log10(padj)"
    ) +
    ggplot2::theme_minimal(base_size = 12)
  ggplot2::ggsave(output_file, chart, width = 10, height = max(6.5, 0.62 * nrow(plot_data) + 2), dpi = 300)
  invisible(TRUE)
}

short_name <- function(library_name) {
  short_names <- c(
    "KEGG_2021_Human" = "kegg",
    "GO_Biological_Process_2023" = "go_bp",
    "GO_Cellular_Component_2023" = "go_cc",
    "GO_Molecular_Function_2023" = "go_mf"
  )
  if (library_name %in% names(short_names)) return(unname(short_names[[library_name]]))
  gsub("[^A-Za-z0-9]+", "_", tolower(library_name))
}

enrichr_request_config <- function() {
  # On this Windows host, the default libcurl route used by enrichR fails while
  # the same endpoint succeeds over IPv4. Keep the service/API unchanged and
  # make the transport choice explicit and auditable.
  httr::config(ipresolve = 1L, connecttimeout = 30L, timeout = 120L)
}

require_success <- function(response, endpoint) {
  code <- httr::status_code(response)
  if (code < 200L || code >= 300L) {
    detail <- tryCatch(httr::content(response, as = "text", encoding = "UTF-8"), error = function(error) "")
    stop("Enrichr ", endpoint, " returned HTTP ", code, ": ", detail, call. = FALSE)
  }
  response
}

submit_gene_list <- function(genes) {
  response <- httr::POST(
    "https://maayanlab.cloud/Enrichr/addList",
    body = list(
      list = paste(genes, collapse = "\n"),
      description = "PSGCL_test BRCA Random-Forest selected genes"
    ),
    encode = "multipart",
    enrichr_request_config()
  )
  response <- require_success(response, "addList")
  payload <- jsonlite::fromJSON(httr::content(response, as = "text", encoding = "UTF-8"))
  if (is.null(payload$userListId) || !nzchar(as.character(payload$userListId))) {
    stop("Enrichr addList response has no userListId.", call. = FALSE)
  }
  payload
}

fetch_library_export <- function(user_list_id, library_name) {
  response <- httr::GET(
    "https://maayanlab.cloud/Enrichr/export",
    query = list(
      userListId = user_list_id,
      filename = paste0(short_name(library_name), "_enrichment"),
      backgroundType = library_name
    ),
    enrichr_request_config()
  )
  response <- require_success(response, paste0("export/", library_name))
  raw_text <- httr::content(response, as = "text", encoding = "UTF-8")
  if (!nzchar(raw_text)) stop("Enrichr returned an empty export for ", library_name, call. = FALSE)
  connection <- textConnection(raw_text)
  on.exit(close(connection), add = TRUE)
  table <- utils::read.delim(
    connection, sep = "\t", header = TRUE, quote = "", comment.char = "",
    stringsAsFactors = FALSE, check.names = FALSE
  )
  list(raw_text = raw_text, table = table)
}

full_arguments <- commandArgs(trailingOnly = FALSE)
script_argument <- grep("^--file=", full_arguments, value = TRUE)
script_path <- if (length(script_argument) == 1L) sub("^--file=", "", script_argument) else "enrichr_brca.R"
default_library <- file.path(Sys.getenv("LOCALAPPDATA"), "PSGCL_test_R", "library")
project_library <- Sys.getenv("PSGCL_R_LIBS", unset = default_library)
dir.create(project_library, recursive = TRUE, showWarnings = FALSE)
.libPaths(unique(c(project_library, .libPaths())))
default_config <- file.path(dirname(normalizePath(script_path, mustWork = FALSE)), "enrichr_config.json")
arguments <- parse_arguments(commandArgs(trailingOnly = TRUE), default_config)

abort_missing_packages(c("jsonlite", "ggplot2", "httr", "curl"))
if (!file.exists(arguments$genes)) stop("Gene hand-off CSV not found: ", arguments$genes, call. = FALSE)
if (!file.exists(arguments$config)) stop("Configuration file not found: ", arguments$config, call. = FALSE)
if (file.exists(arguments$output_dir)) stop("Output directory already exists: ", arguments$output_dir, call. = FALSE)

config <- jsonlite::fromJSON(arguments$config, simplifyVector = FALSE)
libraries <- unlist(config$libraries, use.names = FALSE)
threshold <- as.numeric(config$adjusted_p_value_threshold)
if (length(libraries) == 0L || is.na(threshold) || threshold <= 0 || threshold > 1) {
  stop("Configuration must define non-empty libraries and adjusted_p_value_threshold in (0, 1].", call. = FALSE)
}

selected <- utils::read.csv(arguments$genes, stringsAsFactors = FALSE, check.names = FALSE)
symbol_column <- if ("clean_gene" %in% names(selected)) "clean_gene" else if ("gene_symbol" %in% names(selected)) "gene_symbol" else NULL
if (is.null(symbol_column)) stop("--genes must contain clean_gene or gene_symbol.", call. = FALSE)
raw_column <- if ("raw_gene" %in% names(selected)) "raw_gene" else symbol_column
candidate <- trimws(as.character(selected[[symbol_column]]))
valid <- !is.na(candidate) & nzchar(candidate)
duplicate <- valid & duplicated(candidate)
accepted <- valid & !duplicate

genes_sent <- data.frame(
  submission_rank = seq_len(sum(accepted)),
  raw_gene = as.character(selected[[raw_column]][accepted]),
  clean_gene = candidate[accepted],
  stringsAsFactors = FALSE
)
rejected <- data.frame(
  raw_gene = as.character(selected[[raw_column]][!accepted]),
  clean_gene = candidate[!accepted],
  reason = ifelse(!valid[!accepted], "empty_symbol", "duplicate_symbol"),
  stringsAsFactors = FALSE
)
if (nrow(genes_sent) == 0L) stop("No non-empty, unique genes are available for Enrichr.", call. = FALSE)

dir.create(arguments$output_dir, recursive = TRUE)
raw_directory <- file.path(arguments$output_dir, "raw")
filtered_directory <- file.path(arguments$output_dir, "filtered")
plot_directory <- file.path(arguments$output_dir, "plots")
dir.create(raw_directory)
dir.create(filtered_directory)
dir.create(plot_directory)
utils::write.csv(genes_sent, file.path(arguments$output_dir, "genes_sent_to_enrichr.csv"), row.names = FALSE)
utils::write.csv(rejected, file.path(arguments$output_dir, "genes_rejected_before_enrichr.csv"), row.names = FALSE)

# The enrichR package's default httr call is not usable on this Windows host:
# it cannot connect to Enrichr unless IPv4 is selected. This adapter uses the
# official addList/export Enrichr REST endpoints through httr with IPv4 forced.
# It preserves the same Enrichr service, human libraries, no-background design,
# statistics, and ordering as the retained Python pipeline.
query_time <- format(Sys.time(), tz = "UTC", usetz = TRUE)
submission <- submit_gene_list(genes_sent$clean_gene)
normalised_tables <- list()
library_summary <- list()

for (library_name in libraries) {
  exported <- fetch_library_export(submission$userListId, library_name)
  writeLines(
    exported$raw_text,
    file.path(raw_directory, paste0(short_name(library_name), "_raw.tsv")),
    useBytes = TRUE
  )
  raw_table <- exported$table
  utils::write.csv(raw_table, file.path(raw_directory, paste0(short_name(library_name), "_raw.csv")), row.names = FALSE)
  normalised <- normalise_enrichr_table(raw_table, library_name)
  normalised_tables[[library_name]] <- normalised

  bar_maximum <- config$bar_top_terms[[library_name]]
  if (is.null(bar_maximum)) bar_maximum <- 10L
  dot_maximum <- config$dot_top_terms[[library_name]]
  if (is.null(dot_maximum)) dot_maximum <- 10L
  filtered <- filter_terms(normalised, threshold, as.integer(bar_maximum))
  dot_filtered <- filter_terms(normalised, threshold, as.integer(dot_maximum))
  utils::write.csv(
    filtered,
    file.path(filtered_directory, paste0(short_name(library_name), "_significant_terms_r.csv")),
    row.names = FALSE
  )
  title <- switch(
    library_name,
    "KEGG_2021_Human" = "KEGG Pathway",
    "GO_Biological_Process_2023" = "GO Biological Process",
    "GO_Cellular_Component_2023" = "GO Cellular Component",
    "GO_Molecular_Function_2023" = "GO Molecular Function",
    library_name
  )
  prefix <- short_name(library_name)
  bar_plot_written <- isTRUE(save_bar_plot(
    filtered, title, threshold,
    file.path(plot_directory, paste0(prefix, "_pvalue_barplot_r.png"))
  ))
  dot_plot_written <- isTRUE(save_dot_plot(
    dot_filtered, title,
    file.path(plot_directory, paste0(prefix, "_dotplot_r.png"))
  ))
  library_summary[[library_name]] <- list(
    raw_terms = nrow(raw_table),
    significant_terms_written = nrow(filtered),
    bar_plot_written = bar_plot_written,
    dot_plot_written = dot_plot_written
  )
}

combined <- bind_tables(normalised_tables)
if ("Adjusted P-value" %in% names(combined)) {
  combined <- combined[order(suppressWarnings(as.numeric(combined[["Adjusted P-value"]]))), , drop = FALSE]
}
utils::write.csv(combined, file.path(arguments$output_dir, "enrichment_kegg_go_full_r.csv"), row.names = FALSE)
writeLines(capture.output(sessionInfo()), file.path(arguments$output_dir, "session_info.txt"))

manifest <- list(
  analysis = "BRCA R Enrichr",
  query_time_utc = query_time,
  genes_input = arguments$genes,
  genes_sent = nrow(genes_sent),
  rejected_genes = nrow(rejected),
  organism = config$organism,
  libraries = as.list(libraries),
  adjusted_p_value_threshold = threshold,
  strict_comparison = "Adjusted P-value < threshold",
  background_gene_list = "not supplied in either R or retained Python Enrichr pipeline",
  config = arguments$config,
  enrichr_client = "Enrichr REST addList/export via httr with IPv4 forced",
  enrichr_user_list_id = as.character(submission$userListId),
  enrichr_short_id = as.character(submission$shortId),
  library_summary = library_summary
)
jsonlite::write_json(manifest, file.path(arguments$output_dir, "enrichment_manifest.json"), pretty = TRUE, auto_unbox = TRUE)
cat("R Enrichr completed. Output: ", arguments$output_dir, "\n", sep = "")
